version: '3.8'

services:
  basement-hq:
    build: .
    ports:
      - "8505:8501"
    volumes:
      - ./app:/app
      - /var/run/docker.sock:/var/run/docker.sock
    pid: "host"
    environment:
      - PYTHONUNBUFFERED=1
